pino_website/apps/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name="accounts"
urlpatterns = [
    path("profile", views.ProfileView.as_view(), name="profile"),
    # Django Auth
    path(
        "login",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login"
    ),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
]

pino_website/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import  views as auth_views
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('accounts/profile', views.ProfileView.as_view(), name='profile'),

    #Django Auth
    path('accounts/login', auth_views.LoginView.as_view(template_name="accounts/login.html"), name='login'),
    path('accounts/logout', auth_views.LogoutView.as_view(), name='logout')
]

pino_website/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
'''
class UserProfile：定义了一个模型类 UserProfile，表示与数据库中某个表相关联的对象。
models.Model：这是 Django 提供的基类，用于将 Python 类映射到数据库表。
20250126添加
'''
class UserInterest(models.Model):
   name=models.CharField(max_length=64,unique=True)
   normalized_name=models.CharField(max_length=64,unique=True)
   def __str__(self):
      return self.name
class UserPersona(models.Model):
   name=models.CharField(max_length=64,unique=True)#姓名是唯一的
   normalized_name=models.CharField(max_length=64,unique=True)
   description=models.CharField(max_length=200)
   def __str__(self):
      return self.name

class UserProfile(models.Model):
   user=models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
   is_full_name_displayed=models.BooleanField(default=True)#字段类型：BooleanField，表示一个布尔值字段（True 或 False）。default=True：如果没有显式设置值，默认值为 True。用途：用于指示是否显示用户的全名。
   #detail
   bio=models.CharField(max_length=500,blank=True,null=True)
   #max_length=500：最多可以存储 500 个字符。
   #blank=True：表示该字段在表单中可以留空（前端验证）。
   #null=True：表示该字段在数据库中可以存储 NULL 值。
   #用于存储用户的个人简介
   website=models.URLField(max_length=200,blank=True,null=True)
   #用途：存储用户的个人网站地址
   persona=models.ForeignKey(UserPersona,on_delete=models.SET_NULL,blank=True,null=True)
   interest=models.ManyToManyField(UserInterest,blank=True)

pino_website/apps/accounts/views.py
# Create your views here.
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin




class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/profile.html"

pino_website/views.py
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
def index(request):
    print(request.user)
    return render(request, 'index.html')
    # 这使用模板加载器 loader 来获取 index.html 模板。它基本上是在告诉 Django 去项目的模板目录下查找名为 index.html 的文件
    # template=loader.get_template('index.html')
    # return HttpResponse(template.render({},request))
def about(request):
    return render(request, 'about.html')

def contact(request):
    return render(request, 'contact.html')

class ProfileView(LoginRequiredMixin,TemplateView):
    template_name = "accounts/profile.html"

pino_website/templates/about.html
{%extends 'base.html' %}

{% block title %} About{% endblock %}

{% block content %}
<h1>
    About
</h1>
{% endblock %}

pino_website/templates/accounts/login.html
{%extends 'base.html' %}

{% block title %} Login{% endblock %}

{% block content %}
<h2>Login</h2>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Login</button>
</form>
{% endblock %}

pino_website/templates/accounts/profile.html
{%extends 'base.html' %}

{% block title %} profile{% endblock %}

{% block content %}
<h1>
    {{user.username}}'s profile
</h1>
{% endblock %}

pino_website/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}Pion Yvxiang{% endblock %}</title>
</head>
<body>
{% include 'navbar.html' %}
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

pino_website/templates/contact.html
{%extends 'base.html' %}

{% block title %} Contact{% endblock %}

{% block content %}
<h1>
    Contact
</h1>
{% endblock %}

pino_website/templates/index.html
{%extends 'base.html' %}

{% block title %} Index{% endblock %}

{% block content %}
<h1>
    Template Homepage
</h1>
{% endblock %}

pino_website/templates/navbar.html
<div>
    {% url 'public:index' as index_url %}
    <span>{%if request.path == index_url %}Home{% else %}<a href="{{index_url}}">Home</a>{% endif %}</span>
    {% url 'public:about' as about_url %}
    <span>{%if request.path == about_url %}About{% else %}<a href="{{about_url}}">About</a>{% endif %}</span>
    {% url 'public:contact' as contact_url %}
    <span>{%if request.path == contact_url %}Contact{%else%}<a href="{{contact_url}}">Contact</a>{% endif %}</span>
    <span style="float:right">
        {% if user.is_authenticated %}
            {% url 'accounts:profile' as profile_url %}
            {% url 'accounts:logout' as logout_url %}
           <span>Hi {% if request.path == profile_url%} {{user.username}}{% else %}<a href="{{ profile_url }}">{{user.username}}!</a>{% endif %}</span>
            <form id="logout-form" method="POST" action="{{logout_url}}" style="display: none;">
               {% csrf_token %}
            </form>
            <a href="#" onclick="document.getElementById('logout-form').submit();">Logout</a>
        {% else %}
            {% url 'accounts:login' as login_url %}
            <span><a href="{{login_url}}">Login</a></span>
        {%endif %}
    </span>
</div>